language: java

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
  - mvn coveralls:report